#Auto-Generated by bot on 2016-08-30 16:38

# Here goes your discord bot token.
discord_token="MySuperSecretTokenIShouldNeverShareWithAnyone"

# The game that will be displayed. This can be changed using ?setting name and will automatically be changed here.
game = "I'm a neko"

# These are the default-set permissions. Add or change them as you want.
# Syntax: ["permission", access_level]
default_access = [
    ["help", 0],
    ["play", 0],
    ["apistatus", 0],
    ["dequeue", 1],
    ["anime", 0],
    ["manga", 0],
    ["stats", 0],
    ["btc", 0],
    ["bug", 0],
    ["dig", 0],
    ["excuse", 0],
    ["tag", 0],
    ["getlevel", 0],
    ["skip", 0],
    ["how", 0],
    ["idk", 0],
    ["info", 0],
    ["isup", 0],
    ["serverinfo", 0],
    ["link", 0],
    ["resume", 0],
    ["userinfo", 0],
    ["pause", 0],
    ["anilist", 0],
    ["playing", 0],
    ["8ball", 0],
    ["queue", 0],
    ["volume", 0],
    ["tag_info", 0],
    ["stop", 1],
    ["konachan", 2],
    ["tag_delete_own", 3],
    ["set_announce", 4],
    ["role_remove", 4],
    ["modules", 4],
    ["massban", 4],
    ["unban", 4],
    ["set_banlog", 4],
    ["set_log", 4],
    ["set_quit", 4],
    ["set_welcome", 4],
    ["role_add", 4],
    ["ban", 4],
    ["softban", 4],
    ["kick", 4],
    ["purge", 4],
    ["tag_set", 4],
    ["tag_delete", 4],
    ["autodc", 4],
    ["skip_admin", 4],
    ["dequeue_admin", 4],
    ["name", 5],
    ["nick", 5],
    ["disablecmd", 5],
    ["disabledcmds", 5],
    ["setlevel", 5],
    ["enablecmd", 5],
    ["config", 5],
    ["alias", 5],
]

# These are the default configuration variables set by the bot.
# Just add a new one when you want to.
# Syntax: ["config", "value", "type", "Short description"]
defaultvalues = [
    ["prefix", "!", "str", "The prefix for commands"],
    ["music_bot", True, "bool", "Should the Music bot be active?"],
    ["joined_notification", False, "bool", "Send a message to the server when a user joined the server?"],
    ["left_notification", False, "bool", "Send a message to the server when a user left the server?"],
    ["antispam_enabled", False, "bool", "Should AntiSpam be enabled?"],
    ["antispam_action", "kick", "str", "What should happen to spammers? (kick/ban/move)"],
    ["antispam_move_role", None, "str", "Which role should spammers be moved to?"],
    ["invite_autoban", False, "bool", "Should bot ban ONLY new users for posting invite links?"],
    ["antispam_seconds", 5, "int", "Seconds until the AntiSpam kicks in"],
    ["antispam_messages", 5, "int", "The amount of messages in the given seconds until the AntiSpam kicks in"],
    ["antispam_ignore_level", 4, "int", "Users with this or a higher access level will be ignored by AntiSpam"],
    ["music_bot_volume", 0.2, "float", "Volume of the Music Bot"],
    ["announcement_channel", None, "str", "Join/Quit annoucement channel"],
    ["log_channel", None, "str", "Server log channel"],
    ["ban_log_channel", None, "str", "Ban log channel"],
    ["join_message", "Welcome {mention}!", "str", "New member join message!"],
    ["quit_message", "{mention} left {server}!", "str", "Member leave message."],
    ["unshort_urls", False, "bool", "Should bot automatically unshort shortened URLs?"],
    ["rss_enabled", False, "bool", "Should the bot automatically fetch RSS feeds?"],
]

# The bot administrators can be configured here.
# Syntax: {user_id, "username", access_level}
botadmins = [
    [123456789101112131, "Awesome guy", 6]
]

# Credentials for MySQL
mysql_data = {
    "host": "localhost",
    "user": "supercooluser",
    "password": "supercoolpassword",
    "port": 3306
}

# User credentials for MyAnimeList.net API
myanimelist = {
    "user": "supercooluser",
    "password": "supersecretpassword"
}

# === Do not change anything here.
import os
client = None
music_bots = {}
repl_sess = None
cwd = os.path.dirname(os.path.realpath(__file__))